//* --- Queries

export const GET_TASKS = 'GET_TASKS';
export const GET_LISTS = 'GET_LISTS';
export const GET_TAGS = 'GET_TAGS';
export const GET_STICKY_NOTES = 'GET_STICKY_NOTES';

export const GET_STICKY_NOTE = 'GET_STICKY_NOTE';


//* --- Mutations

export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const ADD_LIST = 'ADD_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const DELETE_LIST = 'DELETE_LIST';

export const ADD_TAG = 'ADD_TAG';
export const DELETE_TAG = 'DELETE_TAG';

export const ADD_STICKY_NOTE = 'ADD_STICKY_NOTE';
export const UPDATE_STICKY_NOTE = 'UPDATE_STICKY_NOTE';
export const DELETE_STICKY_NOTE = 'DELETE_STICKY_NOTE';

export const RESTORE_TASK = 'RESTORE_TASK';
export const RESTORE_LIST = 'RESTORE_LIST';
export const RESTORE_TAG = 'RESTORE_TAG';
export const RESTORE_STICKY_NOTE = 'RESTORE_STICKY_NOTE';

export const DELETE_TASK_PERMANENTLY = 'DELETE_TASK_PERMANENTLY';
export const DELETE_LIST_PERMANENTLY = 'DELETE_LIST_PERMANENTLY';
export const DELETE_TAG_PERMANENTLY = 'DELETE_TAG_PERMANENTLY';
export const DELETE_STICKY_NOTE_PERMANENTLY = 'DELETE_STICKY_NOTE_PERMANENTLY';

export const EMPTY_TRASH = 'EMPTY_TRASH';
